class CellPos:
  FILE_NAME = ['1', '2']
  TABLE_NAME = ['1', '7']
  DB_KIND = ['1', '11']
  SEQUENCE = ['2', '2']
  SEQUENCE_TARGET_COL = ['2', '7']
  DATE_FORMAT = ['3', '7']
  COL_COUNT = ['3', '2']
  ROW_COUNT = ['4', '2']
  DATA_TYPE_FIRST = ['5', '2']
  COLUMNS_FIRST = ['6', '2']
  DATA_ROWS_FIRST = ['7', '2']